# This will be our builder image
FROM golang:alpine

ARG version=0.13.0

ARG revision=main

COPY . /go/src/github.com/helm/chartmuseum

WORKDIR /go/src/github.com/helm/chartmuseum

RUN CGO_ENABLED=0 GOARCH=arm64 GO111MODULE=on go build \
   -v --ldflags="-w -X main.Version=${version} -X main.Revision=${revision}" \
   -o /chartmuseum \
   cmd/chartmuseum/main.go


# This will be the final image
# alpine:3.15.5  arm
FROM alpine@sha256:26284c09912acfc5497b462c5da8a2cd14e01b4f3ffa876596f5289dd8eab7f2

RUN apk add --no-cache cifs-utils ca-certificates

COPY --from=0 /chartmuseum /chartmuseum

USER 1000:1000

ENTRYPOINT ["/chartmuseum"]
